apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-rbd-pvc
  namespace: kube-ops
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: fast