---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: kube-ops
  labels:
    app: jenkins-svc
spec:
  selector:
    app: jenkins
  clusterIP: None
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: agent
      port: 50000
      targetPort: 50000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-svc-ingress
  namespace: kube-ops
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: jenkins.mofangge.net
      http:
        paths:
        - backend:
            serviceName: jenkins-svc
            servicePort: 8080