apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    role: stateful
spec:
  ports:
  - port: 80
    name: web
  selector:
    app: nginx
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: web2
spec:
  serviceName: "nginx"
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        role: stateful
    spec:
      containers:
      - name: nginx
        image: nginx:1.13.12
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
      annotations:
        volume.beta.kubernetes.io/storage-class: "nfs-dynamic-class"
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1G
